config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :holdings

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/holding.rb
class Holding < ApplicationRecord
    validates :crypto, presence: true
    validates :amount, presence: true, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/holdings_controller.rb
class HoldingsController < ApplicationController

    def index
        @holdings = Holding.all
        @portfolio = build_portfolio
    end
    
    def show
        @holding = Holding.find(params[:id])
        @api_string = 'https://api.coinmarketcap.com/v1/ticker/' + @holding[:crypto] + '/'
        @response = HTTParty.get(@api_string)
    end

    def new
        @holding = Holding.new
    end

    def edit
        @holding = Holding.find(params[:id])
    end

    def create
        @holding = Holding.new(holding_params)

        if @holding.save
            redirect_to @holding
        else
            render 'new'
        end
    end

    def update
        @holding = Holding.find(params[:id])

        if @holding.update(holding_params)
            redirect_to @holding
        else
            render 'edit'
        end
    end

    def destroy
        @holding = Holding.find(params[:id])
        @holding.destroy

        redirect_to holdings_path
    end

    # Return CoinMarketCap API response for top 250 coins
    # Change limit to increase the scope
    def all_tokens
        all_tokens = HTTParty.get('https://api.coinmarketcap.com/v1/ticker/?limit=250')
    end

    # Assemble holdings and API request into a portfolio
    def build_portfolio
        @portfolio = Array.new
        @all_tokens = all_tokens
        # @holdings = get_holdings
        @portfolio_names = portfolio_names
        # @names_and_amounts = names_and_amounts(@holdings)
        @all_tokens.each do |token|
            if @portfolio_names.include? token["id"]
                token["amount"] = get_amount(token["id"])
                @portfolio.push(token)
            end
        end
        @portfolio
    end

    # Return the holding amount of a given token
    def get_amount(name)
        @holding = get_holding(name)
        @amount = @holding["amount"]
    end

    # Return specific holding (name and amount)
    def get_holding(name)
        @holding = Holding.find_by crypto: name
    end

    # Return database holdings (names and amounts)
    def get_holdings
        @holdings = Holding.all
    end

    # Collect names of tokens held in the portfolio, used to carve down API results.
    def portfolio_names
        @portfolio_names = Array.new
        @holdings = get_holdings
        @holdings.each do |holding|
            @portfolio_names.push(holding.crypto)
        end
        @portfolio_names
    end

    # def names_and_amounts(holdings)
    #     @names_and_amounts = Array.new
    #     @holdings = holdings
    #     @holdings.each do |holding|
    #         @portfolio_names.push({"name" => holding.crypto, "amount" => holding.amount})
    #     end
    #     @names_and_amounts
    # end

    private
        def holding_params
            params.require(:holding).permit(:crypto, :amount)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/holdings_helper.rb
module HoldingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/holdings/_form.html.erb
<%= form_with model: @holding, local: true do |form| %>

    <% if @holding.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@holding.errors.count, "error") %> prohibited this article from being saved:
            </h2>
            <ul>
                <% @holding.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <p>
        <%= form.label :crypto %><br>
        <%= form.text_field :crypto %>
    </p>

    <p>
        <%= form.label :amount %><br>
        <%= form.text_area :amount %>
    </p>

    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/holdings/edit.html.erb
<h1>Update Holding</h1>

<%= render 'form' %>

<%= link_to 'Portfolio', holdings_path %>

app/views/holdings/index.html.erb
<h1>Your current portfolio</h1>
<br>
<%= link_to 'Input New Holding', new_holding_path %>
<br>

<% @total_usd = 0 %>
<% @total_btc = 0 %>

<table>
    <br>
    <tr>
        <th>Crypto</th>
        <th>Amount</th>
        <th>BTC Total</th>
        <th>USD Total</th>
        <th>BTC Price</th>
        <th>USD Price</th>
        <th>1 HR</th>
        <th>24 HR</th>
        <th>1 WK</th>
    </tr>
    <br>

    <% @portfolio.each do |holding| %>

        <% @btc_value = (holding["amount"].to_f * holding["price_btc"].to_f) %>
        <% @usd_value = (holding["amount"].to_f * holding["price_usd"].to_f) %>

        <% @total_btc += @btc_value %>
        <% @total_usd += @usd_value %>

        <tr>
            <td>
                <%= holding["name"] %>
            </td>
            <td>
                <%= holding["amount"] %>
            </td>
            <td>
                ฿ <%= '%.8f' % @btc_value %>
            </td>
            <td>
                $ <%= '%.2f' % @usd_value %>
            </td>
            <td>
                ฿ <%= '%.8f' % holding["price_btc"].to_f %>
            </td>
            <td>
                $ <%= '%.2f' % holding["price_usd"].to_f %>
            </td>
            <td>
                <%= holding["percent_change_1h"] %> %
            </td>
            <td>
                <%= holding["percent_change_24h"] %> %
            </td>
            <td>
                <%= holding["percent_change_7d"] %> %
            </td>
            <td><%= link_to 'Details', holding_path(holding["id"]) %></td>
            <td><%= link_to 'Update', edit_holding_path(holding["id"]) %></td>
            <td><%= link_to 'Delete', holding_path(holding["id"]), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
</table>
<br>
<strong>Total: </strong>
<p>BTC: ฿ <%= @total_btc.round(8) %></p>
<p>USD: $ <%= @total_usd.round(2) %></p>

app/views/holdings/new.html.erb
<h1>New Holding</h1>
<h3>Input a new token and hold on for dear life.</h3>

<%= render 'form' %>

<%= link_to 'Portfolio', holdings_path %>

app/views/holdings/show.html.erb
<p>
    <strong>Crypto Name:</strong>
    <%= @response[0]["name"] %>
</p>

<p>
    <strong>Holding:</strong>
    <%= @holding.amount %>
</p>

<p>
    <strong>USD Value:</strong>
    <% @usd_value = (@holding.amount.to_f * @response[0]["price_usd"].to_f) %>
    $<%= @usd_value %>
<p>

<p>
    <strong>BTC Value:</strong>
    <% @btc_value = (@holding.amount.to_f * @response[0]["price_btc"].to_f) %>
    <%= @btc_value %>
</p>

<p>
    <strong>Current BTC Price:</strong>
    ฿ <%= @response[0]["price_btc"].to_f.round(8) %>
</p>

<p>
    <strong>Current USD Price:</strong>
    $ <%= @response[0]["price_usd"].to_f.round(2) %>
</p>

<p>
    <strong>1 Hour Change:</strong>
    <%= @response[0]["percent_change_1h"] %> %
</p>

<p>
    <strong>24 Hour Change:</strong>
    <%= @response[0]["percent_change_24h"] %> %
</p>

<p>
    <strong>1 Week Change:</strong>
    <%= @response[0]["percent_change_7d"] %> %
</p>




<%= link_to 'Update', edit_holding_path(@holding) %>
<%= link_to 'Portfolio', holdings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cryptohodler</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Cryptohodler</h1>
<h3>We're hodling, are you sure you need to look?</h3>

<%= link_to 'My Portfolio', controller: 'holdings' %>

<h5>Login</h5>
<p>Login form will go here.</p>
<p>Time since last login: XX:XX:XX</p>